#ifndef AXCEND_FOCUS_CLIENT_LIBRARY_CPP__VISIBILITY_CONTROL_H_
#define AXCEND_FOCUS_CLIENT_LIBRARY_CPP__VISIBILITY_CONTROL_H_

#if defined _WIN32 || defined __CYGWIN__
#ifdef __GNUC__
#define AXCEND_FOCUS_CLIENT_LIBRARY_CPP_EXPORT __attribute__ ((dllexport))
#define AXCEND_FOCUS_CLIENT_LIBRARY_CPP_IMPORT __attribute__ ((dllimport))
#else
#define AXCEND_FOCUS_CLIENT_LIBRARY_CPP_EXPORT __declspec(dllexport)
#define AXCEND_FOCUS_CLIENT_LIBRARY_CPP_IMPORT __declspec(dllimport)
#endif
#ifdef AXCEND_FOCUS_CLIENT_LIBRARY_CPP_BUILDING_DLL
#define AXCEND_FOCUS_CLIENT_LIBRARY_CPP_PUBLIC AXCEND_FOCUS_CLIENT_LIBRARY_CPP_EXPORT
#else
#define AXCEND_FOCUS_CLIENT_LIBRARY_CPP_PUBLIC AXCEND_FOCUS_CLIENT_LIBRARY_CPP_IMPORT
#endif
#define AXCEND_FOCUS_CLIENT_LIBRARY_CPP_PUBLIC_TYPE AXCEND_FOCUS_CLIENT_LIBRARY_CPP_PUBLIC
#define AXCEND_FOCUS_CLIENT_LIBRARY_CPP_LOCAL
#else
#define AXCEND_FOCUS_CLIENT_LIBRARY_CPP_EXPORT __attribute__ ((visibility("default")))
#define AXCEND_FOCUS_CLIENT_LIBRARY_CPP_IMPORT
#if __GNUC__ >= 4
#define AXCEND_FOCUS_CLIENT_LIBRARY_CPP_PUBLIC __attribute__ ((visibility("default")))
#define AXCEND_FOCUS_CLIENT_LIBRARY_CPP_LOCAL  __attribute__ ((visibility("hidden")))
#else
#define AXCEND_FOCUS_CLIENT_LIBRARY_CPP_PUBLIC
#define AXCEND_FOCUS_CLIENT_LIBRARY_CPP_LOCAL
#endif
#define AXCEND_FOCUS_CLIENT_LIBRARY_CPP_PUBLIC_TYPE
#endif

#endif  // AXCEND_FOCUS_CLIENT_LIBRARY_CPP__VISIBILITY_CONTROL_H_